version: '3'

services:
  # uncomment the sendrecv you would like to use
  #
  #sendrecv-gst:
  #  build: ./sendrecv/gst
  #sendrecv-gst-java:
  #  build: ./sendrecv/gst-java
  sendrecv-gst-rust:
    build: ./sendrecv/gst-rust
    network_mode: "host"
  sendrecv-js:
    build: ./sendrecv/js
    network_mode: "host"
    depends_on:
      - signalling
  signalling:
    build: ./signalling
    network_mode: "host"
