version: '3'

services:
  sendrecv-gst-rust:
    build: ./sendrecv
    network_mode: "host"
  sendrecv-js:
    build: ./js
    network_mode: "host"
    depends_on:
      - signalling
  signalling:
    build: ./signalling
    network_mode: "host"
